repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-aws-credentials
      - id: detect-private-key

  - repo: https://github.com/typicode/husky
    rev: v9.0.10
    hooks:
      - id: husky

  - repo: https://github.com/okonet/lint-staged
    rev: v15.2.0
    hooks:
      - id: lint-staged
        additional_dependencies:
          - eslint@^8.56.0
          - prettier@^3.2.5
          - @typescript-eslint/parser@^7.3.1
          - @typescript-eslint/eslint-plugin@^7.3.1

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@^8.56.0
          - prettier@^3.2.5
          - @typescript-eslint/parser@^7.3.1
          - @typescript-eslint/eslint-plugin@^7.3.1
          - eslint-config-prettier@^9.1.0
          - eslint-plugin-prettier@^5.1.3
          - eslint-plugin-react@^7.34.2
          - eslint-plugin-react-hooks@^5.0.0
          - eslint-plugin-import@^2.29.1
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        args:
          - --fix
          - --max-warnings=0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@^3.2.5
          - @trivago/prettier-plugin-sort-imports@^4.2.0
        files: \.(js|jsx|ts|tsx|json|css|scss|md|mdx|html|yml|yaml)$
        args:
          - --write
          - --single-quote
          - --trailing-comma=es5
          - --print-width=100
          - --prose-wrap=always

  - repo: https://github.com/compiler-explorer/compiler-explorer
    rev: v0.1.0
    hooks:
      - id: check-typescript
        name: TypeScript type checking
        entry: npm run type-check
        language: system
        types: [file, typescript]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: validate-package-json
        name: Validate package.json
        entry: node -e "try { require('./package.json'); } catch (e) { console.error('Invalid package.json:', e.message); process.exit(1); }"
        language: node
        types: [file]
        files: package\.json$
        pass_filenames: false
        always_run: true
